version: '3.8'
services:
  dev-database:
    image: mysql:8.1.0 
    container_name: eticket
    ports:
      - 6000:3306 
    environment:
      MYSQL_ROOT_PASSWORD: Abc123456789
      MYSQL_USER: your_username
      MYSQL_PASSWORD: YourPassword123
      MYSQL_DATABASE: testdb
    networks:
      - nestjs-network-mysql
networks:
  nestjs-network-mysql:
